version: '3'
services:
    cyberpecker:
        build:
            dockerfile: Dockerfile
            context: ./
        image: cyberpecker
        container_name: cyberpecker
        env_file:
            - ./.env
        restart: always
        ports:
            - '3000:3000'
        volumes:
            - ./cyberpecker:/cyberpecker
            - /cyberpecker/node_modules
