name: Build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    # Linting Check
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Node Version Setup
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install Dependencies
              run: |
                  echo "Installing Dependencies..."
                  npm install -g yarn
                  yarn install --frozen-lockfile

            - name: Lint Check
              run: |
                  echo "Running Linting Test..."
                  yarn next lint

              env:
                  API_URL: ${{ secrets.API_URL }}

    # Build job
    build:
        runs-on: ubuntu-latest
        needs: [lint]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Node Version Setup
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Building
              run: |
                  echo "Building..."
                  npm install -g yarn
                  yarn install --frozen-lockfile
                  yarn next build

              env:
                  API_URL: ${{ secrets.API_URL }}
